site_name: The DTW suite
theme: 
  name: cinder
  highlightjs: true
  hljs_languages:
    - r
nav:
  - Home: index.md
  - DTW for R: r.md
  - DTW for Python: python.md
  - FAQ: faq.md
copyright: 'DTW is &copy; 2006-2026, distributed under the <a href="https://cran.r-project.org/web/licenses/GPL-3">GPLv3 license terms</a>.'
markdown_extensions:
  - admonition
