# From https://github.com/marketplace/actions/deploy-mkdocs

name: Publish via MkDocs
on:
  push:
    branches:
      - main


#      - name: Install Sphinx
#        run: sudo apt-get install -y python3-sphinx python3-sphinx-bootstrap-theme

jobs:
  apidocs:
    name: Build API docs
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout dtw-python repo
        uses: actions/checkout@v3
        with:
          repository: DynamicTimeWarping/dtw-python 
          path: dtw-python

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: graphviz
          version: 1.0
          
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' 
          cache: 'pip'
          cache-dependency-path: dtw-python/docs/apidocs-requirements.txt

      - run: pip install -r apidocs-requirements.txt

#      - name: Install dependencies
#        run: |
#          sudo apt-get install -y graphviz
#          pip install sphinx sphinx-automodapi sphinx-bootstrap-theme numpy scipy

      - name: Build DTW in-place
        run: pip3 install -e dtw-python

      - name: Build docs
        run: |
           rm -rf dtw-python/docs/api
           make -C dtw-python/docs clean
           make -C dtw-python/docs html
           tar -cvf api-docs.tar -C dtw-python/docs/_build/ html

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: api-docs
          path: api-docs.tar
          if-no-files-found: error 


  site:
    name: Build website
    needs: apidocs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Download API docs
        uses: actions/download-artifact@v3
        with:
          name: api-docs
      
      - name: Extract API docs
        # cp -a dtw-python/docs/_build/html docs/py-api
        run: |
           mkdir -p docs/py-api
           tar -xf api-docs.tar -C docs/py-api
           echo Dir is now...
           ls -lR

      - name: Run MkDocs docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REQUIREMENTS: mkdocs-requirements.txt
