# From https://github.com/marketplace/actions/deploy-mkdocs

name: Publish via MkDocs
on:
  push:
    branches:
      - main


#      - name: Install Sphinx
#        run: sudo apt-get install -y python3-sphinx python3-sphinx-bootstrap-theme

jobs:
  apidocs:
    name: Build API docs
    runs-on: ubuntu-latest
    steps: 
      - name: (API) Checkout dtw-python repo
        uses: actions/checkout@v3
        with:
          repository: DynamicTimeWarping/dtw-python 
          path: dtw-python

      - name: (API) Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' 

      - name: (API) Install dependencies
        run: |
          sudo apt-get install -y graphviz
          pip install sphinx sphinx-automodapi sphinx-bootstrap-theme numpy scipy

      - name: (API) Build DTW in-place
        run: pip3 install -e dtw-python

      - name: (API) Build docs
        run: |
           rm -rf dtw-python/docs/api
           make -C dtw-python/docs clean
           make -C dtw-python/docs html
           
      - name: (API) Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: api-docs
          if-no-files-found: error 
          path: dtw-python/docs/_build/html


  site:
    name: Build website
    needs: apidocs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Download API docs
        uses: actions/download-artifact@v3
        with:
          name: api-docs
      
      - run: |
           ls -lR
           mkdir -p docs/py-api
           cp -a dtw-python/docs/_build/html docs/py-api

      - name: Run MkDocs docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REQUIREMENTS: mkdocs-requirements.txt
