# From https://github.com/marketplace/actions/deploy-mkdocs

name: Publish docs via MkDocs + GitHub Pages
on:
  push:
    branches:
      - main


#      - name: Install Sphinx
#        run: sudo apt-get install -y python3-sphinx python3-sphinx-bootstrap-theme

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Checkout dtw-python repo
        uses: actions/checkout@v3
        with:
          repository: DynamicTimeWarping/dtw-python 
          path: dtw-python

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' 

      - name: Install Sphinx
        run: pip install sphinx sphinx-automodapi sphinx-bootstrap-theme

      - run: sudo apt-get install -y graphviz

      - name: Build API docs
        run: |
           pip3 install -e dtw-python
           rm -rf dtw-python/docs/api
           make -C dtw-python/docs clean
           make -C dtw-python/docs html
           mkdir -p docs/py-api
           cp -a dtw-python/docs/_build/html docs/py-api

      - name: Run MkDocs docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REQUIREMENTS: requirements.txt
